### ISSUE TITLE
Packet profiling hook needs updated for 1.8.9+

### ISSUE THREAD

**Issue by LunNova** [MinimallyCorrect/TickProfiler#41]

**Comment by LunNova** [comment]
Also for 1.10. It's likely the same change will fix both, as I don't believe any changes between 1.8.9 and 1.10 occurred which would conflict.

**Comment by cjm721** [comment]
Think this also needs to be added to the 1.11.2 fix (probably also covered in the same code for 1.8.9).

**Comment by LunNova** [comment]
Yep. Still haven't gotten around to doing this as I haven't personally needed this feature and nobody has asked for it.

Since you're commenting on this issue, do you need it?

**Comment by cjm721** [comment]
Yep, have a server that is using 750MB/h/player when not moving. Also what ever is doing it does not handle dynamic throttling as the lower the window the more packets I am getting  (thinking custom udp or something as usage jumps instead of lowering packet window like tcp would). 

In general I wonder how hard it be to write a out of process stream watcher that does it. Would have to load all the mods network serialization which would be annoying.

**Comment by Baughn** [comment]
I'm up to 1MB/s/player when not moving, see https://www.reddit.com/r/feedthebeast/comments/6j2elh/profiling_bandwidth_usage_on_110_and_up/ ...

I'm about at the point of wanting to write a packet profiler myself, but I'm not really sure where to start. If you like, we can team up.

**Comment by cjm721** [comment]
Up until TP has it you can use the Sampler mod . It has a packet tracker that you can run on the client or server. (Suggest client). It's not nearly as good but you can make it work.

Sent from my HTC

----- Reply message -----

**Comment by LunNova** [comment]
Not spent much time testing this, but it seems to work.
