### ISSUE TITLE
1.9 Support?

### ISSUE THREAD

**Issue by helkarakse** [MinimallyCorrect/TickProfiler#49]
I don't suppose you have a 1.9 support branch?

**Comment by LunNova** [comment]
The 1.10 version should be compatible with 1.9.

It might refuse to run due to version numbers not matching so there probably will need to be yet another branch. :/

edit: I was sort of hoping to skip 1.9 since it's really easy to update mods from 1.9 to 1.10. I can add another branch for it, but are you sure you can't move up to 1.10?

**Comment by helkarakse** [comment]
I'll give it a try and let you know. 

Edit: I only just read the second part. There isn't much out there yet for 1.10. I suppose we could wait, but in the mean time I'll try out 1.10 on the 1.9 server.

**Comment by helkarakse** [comment]
http://i.imgur.com/8byO50O.png Looks like that's a negative, sorry.

**Comment by LunNova** [comment]
There's now a 1.9.4 release: https://jenkins.nallar.me/job/TickProfiler/branch/1.9.4/
