### ISSUE TITLE
nallar.me is down :(

### ISSUE THREAD

**Issue by dvhaldane** [MinimallyCorrect/TickProfiler#58]
Hi nallar,

Your build server appears to be down.  Is this something temporary or am I going to have to try and live my life without the glory of nallar :(

https://jenkins.nallar.me/job/TickProfiler/

**Comment by dvhaldane** [comment]
As of this morning it is now back up.  Thank you!

**Comment by dvhaldane** [comment]
Got home from work to complete the build and It appears the site is back down again.

**Comment by LunNova** [comment]
It's up now, and should stay up.

Was up and down a lot over the past two weeks due to moving house and rewiring and stuff.

![this is dumb](https://cloud.githubusercontent.com/assets/782440/20222745/6b5cc928-a82e-11e6-82d5-931f44e9b9a6.png)

![this is still dumb](https://cloud.githubusercontent.com/assets/782440/20222755/71830510-a82e-11e6-9426-b1035a2f2737.png)

![srsly](https://cloud.githubusercontent.com/assets/782440/20222736/623da290-a82e-11e6-81c7-94fae3d73a39.png)

Will be some more downtime on Saturday and Monday, but not for more than a few hours.

**Comment by dvhaldane** [comment]
@nallar Thanks for the update and for the help. Nice box as well! All you need now is Google Fiber :)

Good luck with your move and glad you're not disappearing!
