### ISSUE TITLE
Unexpected World Change console spam

### ISSUE THREAD

**Issue by merjilin** [MinimallyCorrect/TickProfiler#66]
Hey, I've been sent by an official of SpongeForge because they've said that TickProfiler is causing some tracking issues. Here's the pastebin: http://pastebin.com/8AyTyx46
I'm using TickProfiler-1.10.2.jenkins.31.jar

**Comment by gabizou** [comment]
@nallar getting this again with other server admins, since TickProfiler is included in some modpacks, we're getting this issue more often as spam, and we can't simply tell people to disable sponge's cause tracker error reporting due to other actual errors going unreported otherwise. That being said, you're still eliminating Sponge's injection to wrap around `ITickable.update()` in `World.updateEntities()`, which is preventing Sponge's tracking system from safely wrapping around and entering various phase states to perform block physics and whatnot. I know we've spoken about the changes in the past, so if there's more discussion needed, I'd be willing to continue that discussion.

**Comment by Brend-Smits** [comment]
Hurray! Thanks for the fix! I can now install Tickprofiler again :D

**Comment by LunNova** [comment]
Should now be fixed. Sorry about the delay, I'm afraid you'll be dealing with false reports for some time... :(
